[2024-08-18T00:50:57.469+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-18T00:50:57.482+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_values_TS_27.get_cases_dataset.save_data_to_s3 scheduled__2024-08-11T00:00:00+00:00 [queued]>
[2024-08-18T00:50:57.489+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_values_TS_27.get_cases_dataset.save_data_to_s3 scheduled__2024-08-11T00:00:00+00:00 [queued]>
[2024-08-18T00:50:57.490+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-18T00:50:57.512+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_cases_dataset.save_data_to_s3> on 2024-08-11 00:00:00+00:00
[2024-08-18T00:50:57.524+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=360) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-18T00:50:57.526+0000] {standard_task_runner.py:63} INFO - Started process 614 to run task
[2024-08-18T00:50:57.526+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'predict_values_TS_27', 'get_cases_dataset.save_data_to_s3', 'scheduled__2024-08-11T00:00:00+00:00', '--job-id', '183', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmphso1k_h_']
[2024-08-18T00:50:57.528+0000] {standard_task_runner.py:91} INFO - Job 183: Subtask get_cases_dataset.save_data_to_s3
[2024-08-18T00:50:57.582+0000] {task_command.py:426} INFO - Running <TaskInstance: predict_values_TS_27.get_cases_dataset.save_data_to_s3 scheduled__2024-08-11T00:00:00+00:00 [running]> on host c8cfda02699d
[2024-08-18T00:50:57.662+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ruslan Solarev' AIRFLOW_CTX_DAG_ID='predict_values_TS_27' AIRFLOW_CTX_TASK_ID='get_cases_dataset.save_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-08-11T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-11T00:00:00+00:00'
[2024-08-18T00:50:57.663+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-18T00:50:57.682+0000] {base.py:84} INFO - Using connection ID 'minio_conn' for task execution.
[2024-08-18T00:50:57.683+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from extra.
[2024-08-18T00:50:57.684+0000] {warnings.py:110} WARNING - <string>:9: AirflowProviderDeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead

[2024-08-18T00:50:58.163+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-18T00:50:58.164+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-18T00:50:58.173+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=predict_values_TS_27, task_id=get_cases_dataset.save_data_to_s3, run_id=scheduled__2024-08-11T00:00:00+00:00, execution_date=20240811T000000, start_date=20240818T005057, end_date=20240818T005058
[2024-08-18T00:50:58.222+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-18T00:50:58.237+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-08-18T00:50:58.240+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
