[2024-08-17T02:15:48.671+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-17T02:15:48.681+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predict_values_TS_17.get_cases_dataset.save_data_to_s3 scheduled__2024-08-04T00:00:00+00:00 [queued]>
[2024-08-17T02:15:48.686+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predict_values_TS_17.get_cases_dataset.save_data_to_s3 scheduled__2024-08-04T00:00:00+00:00 [queued]>
[2024-08-17T02:15:48.686+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-17T02:15:48.696+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): get_cases_dataset.save_data_to_s3> on 2024-08-04 00:00:00+00:00
[2024-08-17T02:15:48.703+0000] {warnings.py:110} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=88257) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-08-17T02:15:48.704+0000] {standard_task_runner.py:63} INFO - Started process 88278 to run task
[2024-08-17T02:15:48.704+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'predict_values_TS_17', 'get_cases_dataset.save_data_to_s3', 'scheduled__2024-08-04T00:00:00+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/etl.py', '--cfg-path', '/tmp/tmp7u85qy4n']
[2024-08-17T02:15:48.706+0000] {standard_task_runner.py:91} INFO - Job 84: Subtask get_cases_dataset.save_data_to_s3
[2024-08-17T02:15:48.740+0000] {task_command.py:426} INFO - Running <TaskInstance: predict_values_TS_17.get_cases_dataset.save_data_to_s3 scheduled__2024-08-04T00:00:00+00:00 [running]> on host 08898c2f83c5
[2024-08-17T02:15:48.797+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Ruslan Solarev' AIRFLOW_CTX_DAG_ID='predict_values_TS_17' AIRFLOW_CTX_TASK_ID='get_cases_dataset.save_data_to_s3' AIRFLOW_CTX_EXECUTION_DATE='2024-08-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-04T00:00:00+00:00'
[2024-08-17T02:15:48.799+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-17T02:15:48.813+0000] {base.py:84} INFO - Using connection ID 'minio_conn' for task execution.
[2024-08-17T02:15:48.813+0000] {connection_wrapper.py:387} INFO - AWS Connection (conn_id='minio_conn', conn_type='aws') credentials retrieved from extra.
[2024-08-17T02:15:48.814+0000] {warnings.py:110} WARNING - <string>:9: AirflowProviderDeprecationWarning: extra['host'] is deprecated and will be removed in a future release. Please set extra['endpoint_url'] instead

[2024-08-17T02:15:49.169+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-08-17T02:15:49.169+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-17T02:15:49.176+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=predict_values_TS_17, task_id=get_cases_dataset.save_data_to_s3, run_id=scheduled__2024-08-04T00:00:00+00:00, execution_date=20240804T000000, start_date=20240817T021548, end_date=20240817T021549
[2024-08-17T02:15:49.198+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-17T02:15:49.212+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-17T02:15:49.214+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
